#!/bin/sh

BLANK="#00000000"
DEFAULT="#8ebd6b"
TEXT="#8ebd6b"
WRONG="#8b3434"
BG="#1a1d21"

i3lock \
	--insidever-color=$BG \
	--ringver-color=$TEXT \
	\
	--insidewrong-color=$BG \
	--ringwrong-color=$WRONG \
	\
	--inside-color=$BG \
	--ring-color=$DEFAULT \
	--line-color=$BLANK \
	--separator-color=$BG \
	\
	--greeter-text="󰌾 Type password to unlock" \
	--greeter-pos="ix:iy+50" \
	--verif-text="Verifying..." \
	--wrong-text="Wrong!" \
	--noinput-text="No input" \
	--lock-text="Locking..." \
	--lockfailed-text="Lock failed!" \
	\
	--greeter-color=$TEXT \
	--verif-color=$TEXT \
	--wrong-color=$WRONG \
	--time-color=$TEXT \
	--date-color=$TEXT \
	--layout-color=$TEXT \
	--keyhl-color=$BG \
	--bshl-color=$WRONG \
	\
	--greeter-font="HackNerdFont-Regular" \
	--greeter-size="16" \
	--verif-font="HackNerdFont-Regular" \
	--verif-size="28" \
	--wrong-font="HackNerdFont-Regular" \
	--wrong-size="28" \
	--time-font="HackNerdFont-Regular" \
	--time-size="28" \
	--time-pos="ix:iy-20" \
	--date-font="HackNerdFont-Regular" \
	--date-size="18" \
	\
	--screen 1 \
	--blur 5 \
	--clock \
	--indicator \
	--radius 160 \
	--ring-width 6.0 \
	--time-str="%H:%M:%S" \
	--date-str="%A, %Y-%m-%d"
