#!/usr/bin/env bash
#
# bootstrap stuff.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR"/common

setup_gitconfig () {
    if ! [[ -f git/.gitconfig.symlink ]]; then
        info 'setup gitconfig'

        git_credential='cache'
        if [ "$(uname -s)" == "Darwin" ]
        then
            git_credential='osxkeychain'
        fi

        user ' - What is your github author name?'
        read -r -e git_authorname
        user ' - What is your github author email?'
        read -r -e git_authoremail

        sed -e "s/AUTHORNAME/$git_authorname/g" \
            -e "s/AUTHOREMAIL/$git_authoremail/g" \
            -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
            git/.gitconfig.symlink.example > git/.gitconfig.symlink

        success 'gitconfig'
    fi
}

install_symlinks () {
    info 'installing symlinks'

    local overwrite_all=false backup_all=false skip_all=false

    symlinks=()
    while IFS=" " read -r line; do symlinks+=("$line"); done < <(find -H "$SCRIPT_DIR" -maxdepth 2 -name '*.symlink')

    for src in "${symlinks[@]}"; do
        dst="$HOME/$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done
}

echo ''

setup_gitconfig
install_symlinks

echo ''
echo 'All bootstrapped!'
