#!/usr/bin/env bash
#
# bootstrap stuff.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR"/common

setup_gitconfig () {
    if ! [[ -f "$SCRIPT_DIR"/001_git/.gitconfig ]]; then
        info 'setup gitconfig'

        git_credential='cache'
        if [ "$(uname -s)" == "Darwin" ]; then
            git_credential='osxkeychain'
        fi

        user ' - What is your github author name?'
        read -r -e git_authorname
        user ' - What is your github author email?'
        read -r -e git_authoremail

        sed -e "s/AUTHORNAME/$git_authorname/g" \
            -e "s/AUTHOREMAIL/$git_authoremail/g" \
            -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
            "$SCRIPT_DIR"/001_git/.gitconfig.example > "$SCRIPT_DIR"/001_git/.gitconfig

        success 'gitconfig'
    fi
}

install_symlinks () {
    info "running symlinks : output logged to $LOG_FILE"

    overwrite_all=false backup_all=false skip_all=false

    symlink_files=()
    while IFS=" " read -r line; do symlink_files+=("$line"); done < <(find -H "$SCRIPT_DIR" -maxdepth 2 -name 'symlink.sh' | sort)

    for symlink_file in "${symlink_files[@]}"; do
        info ""
        info "running symlink file $symlink_file"
        info "==========================================="
        info ""
        if ! symlinks=$(sh -c "$symlink_file" 2>&1); then
            fail "failed to run symlink file $symlink_file"
        else
            for link in "${symlinks[@]}"; do
                lines=()
                while IFS=$'\n' read -r line; do lines+=("$line"); done < <(echo "$link" | tr "\n" "\n")
                for line in "${lines[@]}"; do
                    IFS=" " read -r -a parts <<< "$line"
                    link_file "${parts[0]}" "${parts[1]}"
                done
            done
            info ""
            success "finished symlink file $symlink_file"
            info "==========================================="
        fi
    done
}

echo ''

setup_gitconfig
install_symlinks

echo ''
echo 'All bootstrapped!'
