#!/usr/bin/env bash

# Everything in this script is available to all script files

set -eo pipefail

BASE_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export LOG_FILE="$BASE_DIR/debug.log"

info () {
    local cur_date
    cur_date=$(get_date)
    printf "\r%s [ \033[00;34m..\033[0m ] %s\n" "$cur_date" "$1"
}

user () {
    local cur_date
    cur_date=$(get_date)
    printf "\r%s [ \033[0;33m??\033[0m ] %s\n" "$cur_date" "$1"
}

success () {
    local cur_date
    cur_date=$(get_date)
    printf "\r\033[2K%s [ \033[00;32mOK\033[0m ] %s\n" "$cur_date" "$1"
}

fail () {
    local cur_date
    cur_date=$(get_date)
    printf "\r\033[2K%s [\033[0;31mFAIL\033[0m] %s\n" "$cur_date" "$1"
    exit 1
}

log_to_file () {
    local cur_date
    cur_date=$(get_date)
    printf "%s [ %s ] %s\n" "$cur_date" "$1" "$2" >> "$LOG_FILE"

}

get_date () {
    date +"%Y-%m-%dT%H:%M:%S%z"
}

run_command () {
    local msg=$1; shift

    info "$msg"
    info "~~~~~~~~~~~~~~~~~~~~~~~~"
    while [[ $# -gt 0 ]]; do
        if ! eval "$1" 2>&1 | while IFS= read -r line; do info "$line"; done; then
            info ""
            fail "failed!"
        fi
        shift
    done
    info ""
    success "done!"
    info ""
}

link_file () {
    local src=$1 dst=$2

    local overwrite=
    local backup=
    local skip=
    local action=
    local currentSrc=

    local overwrite_all=${overwrite_all:-false}
    local backup_all=${backup_all:-false}
    local skip_all=${skip_all:-false}

    if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]; then
        if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
            currentSrc="$(readlink "$dst")"

            if [ "$currentSrc" == "$src" ]; then
                skip=true
            else
                user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
                    [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
                read -r -n 1 action

                case "$action" in
                    o )
                    overwrite=true
                    ;;
                    O )
                    overwrite_all=true
                    ;;
                    b )
                    backup=true
                    ;;
                    B )
                    backup_all=true
                    ;;
                    s )
                    skip=true
                    ;;
                    S )
                    skip_all=true
                    ;;
                    * )
                    ;;
                esac
            fi
        fi

        overwrite=${overwrite:-$overwrite_all}
        backup=${backup:-$backup_all}
        skip=${skip:-$skip_all}

        if [ "$overwrite" == "true" ]; then
            rm -rf "$dst"
            success "removed $dst"
        fi

        if [ "$backup" == "true" ]; then
            mv "$dst" "${dst}.backup"
            success "moved $dst to ${dst}.backup"
        fi

        if [ "$skip" == "true" ]; then
            success "skipped $src"
        fi
    fi

    if [ "$skip" != "true" ]; then  # "false" or empty
        ln -s "$1" "$2"
        success "linked $1 to $2"
    fi
}

