#!/usr/bin/env bash
#
# Run all installers.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR"/common

# find all installers and run them iteratively
installers=()
while IFS=" " read -r line; do installers+=("$line"); done < <(find . -name install.sh)

echo ''

for installer in "${installers[@]}"; do
    info "running installer $installer"
    if ! output=$(sh -c "$installer" 2>&1); then
        fail "failed to run installer $installer : installer output -> $output"
    else
        success "finished installer $installer : output logged to $LOG_FILE"
        log_to_file ".." "installer $installer output : $output"
    fi
done

echo ''
echo 'All installed!'

