#!/usr/bin/env bash
#
# Run all installers.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR"/common

# find all installers and run them iteratively
installers=()
while IFS=" " read -r line; do installers+=("$line"); done < <(find . -name install.sh | sort)

echo ""

info "running installers : log file -> $LOG_FILE"
for installer in "${installers[@]}"; do
    info ""
    info "==========================================="

    skip_installer=0
    for skip in "${SKIP_INSTALLERS[@]}"; do
        if echo "$installer" | grep "_$skip/" > /dev/null; then
            skip_installer=1
            break
        fi
    done

    if [[ $skip_installer -eq 1 ]]; then
        warn "skipping installer $installer"
        info "==========================================="
        continue
    else
        info "running installer $installer"
        info ""
    fi

    if ! sh -c "$installer"; then
        fail "failed to run installer $installer"
    else
        success "finished installer $installer"
    fi

    info "==========================================="
done

echo ""
echo "All installed!"

