#!/usr/bin/env bash
#
# setup macos stuff.

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR"/common

if [[ $OSTYPE == "darwin"* ]]; then
    info "installing brew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    success "installed brew"

    if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
        info "installing oh-my-zsh"
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        success "installed oh-my-zsh"
    fi
else
    fail "this script can only be run on macos"
fi

