#!/bin/bash

# From https://stackoverflow.com/a/70954292
if ! [[ "$0" =~ ".bare/hooks/post-checkout" ]] || ! [[ "$1" == "0000000000000000000000000000000000000000" ]]; then
    echo "WARNING: post-checkout hook running for reason otherwise than git worktree add, bailing"
    exit 0
fi

if [[ -f poetry.lock ]]; then
    >&2 echo
    >&2 echo "========================"
    >&2 echo "Running poetry install"
    >&2 echo "========================"
    >&2 echo
    poetry install
fi

if [[ -f pyproject.toml ]] && [[ -f $HOME/pyrightconfig.json ]]; then
    >&2 echo
    >&2 echo "==============================="
    >&2 echo "Linking pyrightconfig.json file"
    >&2 echo "==============================="
    >&2 echo
    ln -s $HOME/pyrightconfig.json pyrightconfig.json
fi
