#!/bin/bash

# From https://github.com/tpope/vim-obsession/issues/11
# Auto start vim-obession when starting nvim with no args
if test -d "$1"; then
    cd "$1" || exit
    if test -f Session.vim; then
        env nvim -S
    else
        env nvim -c Obsession .
    fi
elif test $# -gt 0; then
    env nvim "$@"
elif test -f Session.vim; then
    env nvim -S
else
    env nvim -c Obsession
fi
