#!/bin/bash

# From https://peterlyons.com/problog/2018/01/zsh-lazy-loading/

# Setup Python version manager
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$("$PYENV_ROOT"/bin/pyenv init -)"

# Invoke the real pyenv function now
pyenv "$@"
