#!/bin/bash

# From https://peterlyons.com/problog/2018/01/zsh-lazy-loading/

# Setup Ruby version manager
eval "$("$HOME"/.rbenv/bin/rbenv init - zsh)"
if [[ $OSTYPE == "darwin"* ]]; then
    RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
    export RUBY_CONFIGURE_OPTS
fi

# Invoke the real rbenv function now
rbenv "$@"
