prSections:
  - title: My PRs
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Mentions
    filters: is:open mentions:@me -author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: false
    width: 125
  prsLimit: 30
  issuesLimit: 10
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 40
      author:
        width: 30
      assignees:
        width: 20
      base:
        width: 15
      lines:
        width: 20
    issues:
      updatedAt:
        width: 7
      repo:
        width: 40
      creator:
        width: 30
      assignees:
        width: 20
  refetchIntervalMinutes: 30
repoPaths:
  default_path: ~/Workspace
keybindings:
  prs:
    - key: C
      command: >
        clear &&
        cd {{.RepoPath}} && 
        gitw-add {{.HeadRefName}} || sleep 2
    - key: D
      command: >
        clear &&
        cd {{.RepoPath}} && 
        gitw-add {{.HeadRefName}} "git pull > /dev/null && nvim . -c 'sleep! 250m | DiffviewOpen origin/{{.BaseRefName}}..HEAD'"
    - key: E
      command: >
        clear &&
        cd {{.RepoPath}} && 
        gitw-add {{.HeadRefName}} "git pull > /dev/null && nvim . -c 'sleep! 250m | Octo pr edit {{.PrNumber}}'"
    - key: T
      command: >
        clear &&
        open $BASE_TICKETS_URL$(get-ticket-number {{.HeadRefName}}) || sleep 2
    - key: U
      command: >
        clear &&
        cd {{.RepoPath}} && 
        gitw-add {{.HeadRefName}} "gitw-rebase {{.BaseRefName}} && git push --force"
  issues: []
pager:
  diff: delta
confirmQuit: true
theme:
  ui:
    table:
      compact: true
      showSeparator: false
  colors:
    text:
      primary: "#a0a8b7"
      secondary: "#7a818e"
      inverted: "#0e1013"
      faint: "#7a818e"
      warning: "#e55561"
      success: "#98c379"
    background:
      selected: "#272731"
    border:
      primary: "#31353f"
      secondary: "#31353f"
      faint: "#31353f"
