prSections:
  - title: My PRs
    filters: is:open assignee:@me
    layout:
      author:
        hidden: true
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Mentions 
    filters: is:open mentions:@me -author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: false
    width: 125
  prsLimit: 100
  issuesLimit: 100
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 40
      author:
        width: 30
      assignees:
        width: 20
      base:
        width: 15
      lines:
        width: 20
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
repoPaths:
  default_path: ~/Workspace
keybindings:
  prs:
    - key: C
      command: >
        clear &&
        cd {{.RepoPath}} && 
        gitw-add {{.HeadRefName}}
    - key: d
      command: >
        clear &&
        gh pr diff {{.PrNumber}} -R {{.RepoName}}
  issues: []
pager:
  diff: delta
theme:
  ui:
    table:
      showSeparator: false
  colors:
    text:
      primary: "#a0a8b7"
      secondary: "#7a818e"
      inverted: "#0e1013"
      faint: "#7a818e"
      warning: "#e55561"
      success: "#98c379"
    background:
      selected: "#272731"
    border:
      primary: "#31353f"
      secondary: "#31353f"
      faint: "#31353f"
